# Generated by Django 5.1.3 on 2024-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
